# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the `main` branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to `main`

jobs:
  build:
    runs-on: ubuntu-latest  # Use a virtual machine with Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out your code to the CI runner

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set your Node.js version (can be customized)
    
    - name: Install dependencies
      run: |
        npm install  # or `yarn install` if you're using Yarn

    - name: Run tests
      run: |
        npm test  # or the appropriate test command for your project
